import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { fetchApi } from "../utils/fetchApi";
import { baseUrl } from "../utils/fetchApi";

import { Box, Flex, Text, Button } from "@chakra-ui/react";
import Banner from "../components/Banner";
import axios from "axios";
import Property from "../components/Property";

export default function Home({ propertyForSale, propertyForRent }) {
  // console.log(propertyForSale);
  return (
    <Box>
      <Head>
        <title>Realtor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        purpose="RENT A HOME"
        title1="Rental Homes for"
        title2="Everyone"
        desc1="Explore Apartments, Villas, Homes"
        desc2="and more"
        buttonText="Explore Renting"
        linkName="/search?purpose=for=rent"
        imageUrl="https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmVhbHRvcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
      />
      <Flex flexWrap="wrap">
        {propertyForSale?.map((property) => (
          <Property property={property} key={property.id} />
        ))}
      </Flex>
      <Banner
        purpose="BUY A HOME"
        title1="Find, Buy & Own Your"
        title2="Dream Home"
        desc1="Explore Apartments, Villas, Homes"
        desc2="and more"
        buttonText="Explore Buying"
        linkName="/search?purpose=for=sale"
        imageUrl="https://images.unsplash.com/photo-1601760561441-16420502c7e0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVhbHRvcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
      />
      <Flex flexWrap="wrap">
        {propertyForRent?.map((property) => (
          <Property property={property} key={property.id} />
        ))}
      </Flex>
    </Box>
  );
}

export const getStaticProps = async () => {
  const propertyForSale = await fetchApi(
    `${baseUrl}/properties/list?locationExternalIDs=5002%2C6020&purpose=for-sale&hitsPerPage=6`
  );
  const propertyForRent = await fetchApi(
    `${baseUrl}/properties/list?locationExternalIDs=5002%2C6020&purpose=for-rent&hitsPerPage=6`
  );

  return {
    props: {
      propertyForSale: propertyForSale?.hits,
      propertyForRent: propertyForRent?.hits,
    },
  };
};
